import { Router } from "express";
import { dashboard, users, createAdminDraw, simulate, publish, charities, createCharity, updateCharity, deleteCharity, winners, approve, reject, pay } from "../controllers/admin.controller.js";
import { authenticate } from "../middleware/auth.middleware.js";
import { requireAdmin } from "../middleware/role.middleware.js";
import { asyncHandler } from "../utils/asyncHandler.js";
const router = Router();
router.use(authenticate, requireAdmin);
router.get("/dashboard", asyncHandler(dashboard));
router.get("/users", asyncHandler(users));
router.post("/draws", asyncHandler(createAdminDraw));
router.post("/draws/:id/simulate", asyncHandler(simulate));
router.post("/draws/:id/publish", asyncHandler(publish));
router.get("/charities", asyncHandler(charities));
router.post("/charities", asyncHandler(createCharity));
router.put("/charities/:id", asyncHandler(updateCharity));
router.delete("/charities/:id", asyncHandler(deleteCharity));
router.get("/winners", asyncHandler(winners));
router.post("/winners/:id/approve", asyncHandler(approve));
router.post("/winners/:id/reject", asyncHandler(reject));
router.post("/winners/:id/pay", asyncHandler(pay));
export default router;
